-- Magnitude analysis

-- find the total customers by country

SELECT
country,
COUNT(customer_key) AS Total_customer
FROM gold_dim_customers
GROUP BY country 
ORDER BY Total_customer DESC
;

-- find the total customer by gender

SELECT
gender,
COUNT(customer_key) AS Total_customer
FROM gold_dim_customers
GROUP BY gender
ORDER BY Total_customer DESC
;

-- total products by category

SELECT 
category,
COUNT(product_key) AS Total_products
FROM gold_dim_products
GROUP BY category
ORDER BY Total_products DESC ;

-- Average cost in each category

SELECT 
category,
AVG(cost) AS Avg_cost
FROM gold_dim_products
GROUP BY category
ORDER BY Avg_cost DESC ;

-- total revenue generated for each category

SELECT
p.category,
SUM(s.sales_amount) AS Total_revenue
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_products AS p
	ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC
;

-- total revenue generated by each customer

SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) AS Total_revenue
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_revenue DESC
;

-- what is the distribution of sold items across countries

SELECT
c.country,
SUM(s.quantity) AS Total_sold_quantity
FROM gold_fact_sales AS s
LEFT JOIN gold_dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Total_sold_quantity DESC
;

